site_name: Mercury
site_description: A personal blog about various topics
site_author: Your Name
site_url: https://www.bbvaaifactory.com/mercury/

docs_dir: docs
site_dir: site

theme:
  name: 'material'
  language: en
  # custom_dir: overrides
  logo: assets/bbva_white.png
  homepage: https://www.bbvaaifactory.com/mercury/
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.footnote.tooltips
  font:
    text: Lato
  palette: 
    # - media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://es.linkedin.com/showcase/bbva-ai-factory/
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/bbva_aifactory
  generator: false

extra_css:
- stylesheets/extra.css
extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags
  - meta
  - blog:
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_submodules: true
            merge_init_into_class: true
            docstring_style: google

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: 2025 BBVA AI Factory